# kbvc/utils/lock.py
"""
Lock file writer — writes kbvc.lock after every successful commit.

kbvc.lock is the package-lock.json equivalent for knowledge bases:
it records the exact embedding model and vector store configuration so
that anyone cloning this repo knows exactly what backend to set up.

Credentials (API keys, URLs) are NEVER written to the lock file.
Only provider names and model identifiers.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from kbvc import __version__ as _KBVC_VERSION

KBVC_VERSION = _KBVC_VERSION  # kept as a module-level name for compatibility


def write_lock_file(
    lock_path: Path,
    config: dict,
    embed_backend: Any,  # EmbedBackend — avoid circular import
) -> None:
    """
    Rewrite kbvc.lock after a successful commit.
    Uses yaml.dump if pyyaml is available; falls back to manual YAML for robustness.
    """
    data = {
        "kbvc_version": KBVC_VERSION,
        "format_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "embedding": {
            "provider": config.get("embed.backend", ""),
            "model": getattr(embed_backend, "model_name", config.get("embed.model", "")),
            "dims": embed_backend.dimensions,
        },
        "vector_store": {
            "provider": config.get("vectordb.backend", ""),
            "collection": config.get("vectordb.collection", "kbvc"),
            "schema_version": 1,  # bumped by kbvc migrate schema (future)
        },
        "retrieval": {
            "profile": config.get("retrieval.profile", "vector"),
            "hop_depth": int(config.get("retrieval.hop_depth", 2)),
            "top_k": int(config.get("retrieval.top_k", 5)),
            "weight_semantic": float(config.get("retrieval.weight_semantic", 0.7)),
            "weight_graph": float(config.get("retrieval.weight_graph", 0.3)),
        },
    }

    comment = (
        "# kbvc.lock — auto-generated by KBVC. "
        "Commit this file. Do not edit manually.\n"
    )

    try:
        import yaml  # P7: pyyaml is in core deps but guard defensively
        content = comment + yaml.dump(data, default_flow_style=False)
    except ImportError:
        # Manual YAML fallback (P7 pitfall)
        content = comment + _dict_to_yaml(data)

    lock_path.write_text(content, encoding="utf-8")


def _dict_to_yaml(d: dict, indent: int = 0) -> str:
    """Minimal YAML serialiser (no external dependency)."""
    lines = []
    prefix = "  " * indent
    for k, v in d.items():
        if isinstance(v, dict):
            lines.append(f"{prefix}{k}:")
            lines.append(_dict_to_yaml(v, indent + 1))
        elif isinstance(v, str):
            lines.append(f'{prefix}{k}: "{v}"')
        else:
            lines.append(f"{prefix}{k}: {v}")
    return "\n".join(lines) + "\n"
